server:
  port: 8082

spring:
  application:
    name: user-service

  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_office?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

  # Redis配置（暂时注释掉，简化测试）
#  redis:
#    host: localhost
#    port: 6379
#    password: redis123
#    database: 0
#    timeout: 3000ms

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.smartoffice.common.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

# JWT配置
jwt:
  secret: smart-office-secret-key-2024-very-long-secret-for-hs512-algorithm-minimum-512bits
  expiration: 86400000  # 24小时（毫秒）
  header: Authorization
  prefix: Bearer

# 日志配置
logging:
  level:
    com.smartoffice: debug
    org.springframework: info
