version: '3.8'

services:
  # MQTT服务器
  emqx:
    image: emqx/emqx:5.0.0
    container_name: smart-office-emqx
    ports:
      - "1883:1883"        # MQTT端口
      - "8083:8083"        # WebSocket端口
      - "8084:8084"        # WSS端口
      - "8883:8883"        # MQTT SSL端口
      - "18083:18083"      # Dashboard端口
    environment:
      - EMQX_NAME=smart-office
      - EMQX_HOST=127.0.0.1
    volumes:
      - ./emqx/data:/opt/emqx/data
      - ./emqx/log:/opt/emqx/log
    networks:
      - smart-office-network
    restart: unless-stopped

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: smart-office-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=smart_office
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - smart-office-network
    restart: unless-stopped

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: smart-office-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - ./redis/data:/data
    networks:
      - smart-office-network
    restart: unless-stopped

networks:
  smart-office-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  emqx-data:
